### PR TITLE
Adding missing export definition

### PR DESCRIPTION
**Pull request by Karankang007**

### CODE REVIEW

**Comment by Qix-** [comment]
This doesn't do anything - it's a no-op. `cs.get` is overwritten directly below it.

**Comment by Karankang007** [comment]
I know but without this webpack import does not work:

import { get } from ‘color-string’

This works though:

import { to } from ‘color-string’

**Comment by Qix-** [comment]
Yeah that's the problem with webpack, its static analysis is... bad.

Fine, but I'm doing this begrudgingly. Tooling should be better at detecting this.

**Comment by Qix-** [comment]
Released as `1.5.3`.

Thanks for the PR.

**Comment by Karankang007** [comment]
Thanks!

**Pull request merged**
