### PR TITLE
better hsla regex

### PR DESCRIPTION
**Pull request by Nakilon**
Also I see no need to `% 360` twice.

### CODE REVIEW

**Comment by Nakilon** [comment]
Smth wrong with Travis?

**Comment by Qix-** [comment]
Yeah, your changes break the tests. Did you run the tests locally before submitting the PR? Did they pass? Otherwise, some of the tests might be broken (though I'm not sure how).

**Comment by Nakilon** [comment]
Fixed.

**Comment by Qix-** [comment]
Thank you, apologies for the delay.

**Pull request merged**
