### PR TITLE
Add support for space-separated RGB

### PR DESCRIPTION
**Pull request by JJC1138**
This is almost exactly the same as @htunnicliff's excellent PR #55, but just for the RGB case instead of HSL. It adds support for values like:
```
rgb(255 255 255)
rgb(255 255 255 / 1)
```

The motivation for this was that Chrome's developer tools now uses that form of notation for RGB colors, and I got bitten by blindly copying and pasting one into my CSS 😅

### CODE REVIEW

**Comment by clytras** [comment]
Thank you @JJC1138 for the awesome work!

@Qix- please merge and release, we need this!

**Comment by JJC1138** [comment]
> Does the RE support alpha percentage like `rgb(0 255 38 / 7%)`?

No, I'm afraid not. I thought that was disallowed by [the spec](https://www.w3.org/TR/css-color-4/#funcdef-rgb), but I see was wrong 😣 Sorry about that. I'm not using the library in my project anymore so I don't have an immediate need to work on that myself. You're very welcome to fork my branch to add support, of course.

**Comment by clytras** [comment]
@JJC1138 I just fix it to work with alpha percentage and added more tests. Everything passes and it works.

Please check this PR https://github.com/JJC1138/color-string/pull/1 and merge.

**Comment by JJC1138** [comment]
Done. Thanks very much!

**Comment by Qix-** [comment]
Thanks :)

**Comment by Qix-** [comment]
Published as `1.7.0`.

**Comment by clytras** [comment]
You're very welcome @Qix- , thank you for making this!

Now that I'm looking at it again, I think I should have used `parseFloat` for the percentage instead of `parseInt`. The spec says that it's a number, not an integer, thus it may have floating point numbers. What do you think?

**Comment by Qix-** [comment]
PR welcome. :)

**Pull request merged**
